### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by WarwickMasson** [rubenpt91/MP-DocVQA-Framework#6]
Please can you add a license to this project? Right now without a license [it defaults to all rights reserved](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

**Comment by rubenpt91** [comment]
Thanks for your interest. I have added MIT license to allow everyone to use it without restrictions.

**Comment by rubenpt91** [comment]
Thanks for your interest. I have added MIT license to allow everyone to use it without restrictions.
